source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CoreView_Example', :exclusive => true do
  pod 'CoreView', :path => '../'
end

target 'CoreView_Tests', :exclusive => true do
  pod 'CoreView', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
